### ISSUE TITLE
Conflict in wrangler.toml between miniflare and wrangler when using esbuild

### ISSUE THREAD

**Issue by PaganMuffin** [mrbbot/miniflare#7]
When using [esbuild](https://miniflare.dev/recipes/esbuild.html) everything works in miniflare just fine, but when trying use `wrangler dev` it's showing error ```Error: unknown field `main`, there are no fields``` which relates to `main` in `[build.upload]`.
According to [Workers Docs](https://developers.cloudflare.com/workers/cli-wrangler/configuration#build) field `main` is supported in `modules` format (beta for paid plan).
After deleting it miniflare stop working with ```[mf:err] MiniflareError: No script defined, either include it explicitly, or set build.upload.main in Wrangler configuration``` and wrangler dev is building and work fine.

./src/index.js
```javascript
import { handler } from "./m";

addEventListener("fetch", (event) => {
  event.respondWith(handler());
});
```

./src/m.js
```javascript
const handler = () => {
    return new Response("12345")
}

export {handler}
```

package.json
```
{
    "private": true,
    "name": "backend",
    "version": "1.0.0",
    "description": "A template for kick starting a Cloudflare Workers project",
    "main": "./dist/index.js",
    "scripts": {
        "build": "esbuild --bundle --sourcemap --outdir=dist ./src/index.js",
        "dev": "miniflare --watch --debug"
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "devDependencies": {
        "esbuild": "^0.12.15",
        "miniflare": "^1.1.0"
    }
}
```

wrangler.toml
```toml
name = "backend"
type = "javascript"
account_id = "XXXXXXXX"
workers_dev = true
route = ""
zone_id = ""

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"
main = "index.js" ## this

[miniflare]
host = "127.0.0.1"                 ## --host
port = 8787                        ## --port
```

```
npm -v
7.19.1

node -v
v16.4.2

wrangler --version
wrangler 1.17.0

miniflare --version
1.1.0
```
